const Images = {
    SliderTwo: require('@/assets/images/SilderTwo.png'),
    RoastedPumkin:require("@/assets/images/RoastedPumkin.png"),
    LetGetStartImage:require("@/assets/images/LetGetStartImage.png"),
    ProgesteroneExcitedCalmer:require("@/assets/images/ProgesteroneExcitedCalmer.png"),
    ProgesteroneSuperExcitedCalmer:require("@/assets/images/ProgesteroneSuperExcitedCalmer.png"),
    ProgesteroneOneEyeCalmer:require("@/assets/images/ProgesteroneOneEyeCalmer.png"),
    ProgesteroneCalmer:require("@/assets/images/ProgesteroneCalmer.png"),
    ProgesteroneSadCalmer:require("@/assets/images/ProgesteroneSadCalmer.png"),
    ProgesteroneVerySadCalmer:require("@/assets/images/ProgesteroneVerySadCalmer.png"),
    CompanyLogo:require("@/assets/images/CompanyLogo.png"),
    FollowupDialog:require("@/assets/images/FollowupDialog.png"),
    BellyImage:require("@/assets/images/BellyImage.png"),
    RatioDialog:require("@/assets/images/RatioDialog.png"),
    LifeCycleMenuDailog:require("@/assets/images/LifeCycleMenuDailog.png"),
    Nutrition7Dailog:require("@/assets/images/Nutrition7Dailog.png"),
    BottomGradient:require("@/assets/images/BottomGradient.png"),
    TopGradient:require("@/assets/images/TopGradient.png"),
    ProgressTopGradient:require("@/assets/images/ProgressTopGradient.png"),
    BMIImage:require("@/assets/images/BMIImage.png"),
    LifeCycleMenu:require("@/assets/images/LifeCycleMenu.png"),
    GraphicAppscreenshot1: require('./GraphicAppscreenshot1.png'),
    GraphicAppscreenshot2: require('./GraphicAppscreenshot2.png'),
    GraphicAppscreenshot3: require('./GraphicAppscreenshot3.png'),
    GraphicTestosterone1: require('./GraphicTestosterone1.png'),
    GraphicProgesterone1: require('./GraphicProgesterone1.png'),
    IconInsight: require('./IconInsight.png'),
    BloodReport: require('./Blood Report.png'),
    // Characters
    GraphicLHDefault: require('./characters/GraphicLHDefault.png'),
    GraphicEstrogenDefault: require('./characters/GraphicEstrogenDefault.png'),
    GraphicProgesteroneDefault: require('./characters/GraphicProgesteroneDefault.png'),
    GraphicGnRHDefault: require('./characters/GraphicGnRHDefault.png'),
    GraphicFSHDefault: require('./characters/GraphicFSHDefault.png'),
    GraphicTestosteroneDefault: require('./characters/GraphicTestosteroneDefault.png'),
    
}

export default Images;